### PR TITLE
Allow extra fields in sentreports.log

### PR DESCRIPTION
**Pull request by mgedmin**
I want to change gtimelog to write to this file natively, and I want it to also record the destination email.

Because I'm often sending test reports to myself, and I'd like to distinguish those from real reports aferwards.

### CODE REVIEW

**Comment by sirex** [comment]
Maybe instead of adding possibility to write any extra fields, just `destination` field could be added? Strict schema is easier to manage compared to dynamic.

**Comment by mgedmin** [comment]
+1

**Comment by mgedmin** [comment]
Do you want me to do it?

(I don't want to do it.)

**Comment by sirex** [comment]
Yes. Because currently I don't have time.

**Pull request merged**
